/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author flia montoya guzman
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnEscritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuAProductos = new javax.swing.JMenuItem();
        MenuAProveedores = new javax.swing.JMenuItem();
        MenuAPersonal = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuAInformeDeVentas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuClientes = new javax.swing.JMenu();
        MenuCRegistro = new javax.swing.JMenuItem();
        MenuCCreditos = new javax.swing.JMenuItem();
        MenuMovimientos = new javax.swing.JMenu();
        MenuMVentas = new javax.swing.JMenuItem();
        MenuMPedidos = new javax.swing.JMenuItem();
        MenuMDevoluciones = new javax.swing.JMenuItem();
        MenuMTraslados = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        MenuAQuienesSomos = new javax.swing.JMenuItem();
        MenuAAcercade = new javax.swing.JMenuItem();
        MenuGestion = new javax.swing.JMenu();
        MenuGUsuarios = new javax.swing.JMenuItem();
        MenuGCambioUsuario = new javax.swing.JMenuItem();
        MenuGCambioClave = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuGSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boutique Trapitos");

        dpnEscritorio.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnEscritorioLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dpnEscritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        MenuArchivo.setText("Archivo");

        MenuAProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416782037_inventory-maintenance.png"))); // NOI18N
        MenuAProductos.setText("Productos");
        MenuArchivo.add(MenuAProductos);

        MenuAProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416782277_briefcase.png"))); // NOI18N
        MenuAProveedores.setText("Proveedores");
        MenuAProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAProveedoresActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuAProveedores);

        MenuAPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1417481516_Manager.png"))); // NOI18N
        MenuAPersonal.setText("Personal");
        MenuAPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAPersonalActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuAPersonal);
        MenuArchivo.add(jSeparator1);

        MenuAInformeDeVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416782383_reports.png"))); // NOI18N
        MenuAInformeDeVentas.setText("Informes de ventas");
        MenuArchivo.add(MenuAInformeDeVentas);
        MenuArchivo.add(jSeparator2);

        jMenuBar1.add(MenuArchivo);

        MenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416781249_clients.png"))); // NOI18N
        MenuClientes.setText("Clientes");

        MenuCRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416783073_Usercard_01.png"))); // NOI18N
        MenuCRegistro.setText("Registro de clientes");
        MenuClientes.add(MenuCRegistro);

        MenuCCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416783142_credit_card.png"))); // NOI18N
        MenuCCreditos.setText("Créditos");
        MenuClientes.add(MenuCCreditos);

        jMenuBar1.add(MenuClientes);

        MenuMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/areas.png"))); // NOI18N
        MenuMovimientos.setText("Movimientos");

        MenuMVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416783446_currency_dollar green.png"))); // NOI18N
        MenuMVentas.setText("Ventas");
        MenuMovimientos.add(MenuMVentas);

        MenuMPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416786813_box.png"))); // NOI18N
        MenuMPedidos.setText("Pedidos");
        MenuMovimientos.add(MenuMPedidos);

        MenuMDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416791027_Rotation.png"))); // NOI18N
        MenuMDevoluciones.setText("Devoluciones");
        MenuMovimientos.add(MenuMDevoluciones);

        MenuMTraslados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416791187_lorry.png"))); // NOI18N
        MenuMTraslados.setText("Traslados");
        MenuMovimientos.add(MenuMTraslados);

        jMenuBar1.add(MenuMovimientos);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ayuda.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");

        MenuAQuienesSomos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ayuda2.png"))); // NOI18N
        MenuAQuienesSomos.setText("Quiénes Somos");
        MenuAyuda.add(MenuAQuienesSomos);

        MenuAAcercade.setText("Acerca de");
        MenuAyuda.add(MenuAAcercade);

        jMenuBar1.add(MenuAyuda);

        MenuGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416781552_System.png"))); // NOI18N
        MenuGestion.setText("Gestión");

        MenuGUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416791860_User group.png"))); // NOI18N
        MenuGUsuarios.setText("Usuarios");
        MenuGUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGUsuariosActionPerformed(evt);
            }
        });
        MenuGestion.add(MenuGUsuarios);

        MenuGCambioUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416791637_Refresh.png"))); // NOI18N
        MenuGCambioUsuario.setText("Cambio de Usuario");
        MenuGCambioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGCambioUsuarioActionPerformed(evt);
            }
        });
        MenuGestion.add(MenuGCambioUsuario);

        MenuGCambioClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416791814_lock.png"))); // NOI18N
        MenuGCambioClave.setText("Cambio de clave");
        MenuGestion.add(MenuGCambioClave);
        MenuGestion.add(jSeparator3);

        MenuGSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1416791928_Delete.png"))); // NOI18N
        MenuGSalir.setText("Salir");
        MenuGSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGSalirActionPerformed(evt);
            }
        });
        MenuGestion.add(MenuGSalir);

        jMenuBar1.add(MenuGestion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpnEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuGUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGUsuariosActionPerformed
       VentanaUsuarios cUsuarios = new VentanaUsuarios();
       dpnEscritorio.add(cUsuarios);
       cUsuarios.show();
    }//GEN-LAST:event_MenuGUsuariosActionPerformed

    private void MenuGSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuGSalirActionPerformed

    private void MenuAPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAPersonalActionPerformed
        VentanaPersonal cPersonal = new VentanaPersonal();
        dpnEscritorio.add(cPersonal);
        cPersonal.show();
    }//GEN-LAST:event_MenuAPersonalActionPerformed

    private void MenuAProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAProveedoresActionPerformed
        VentanaProveedores cProveedores = new VentanaProveedores();
        dpnEscritorio.add(cProveedores);
        cProveedores.show();
    }//GEN-LAST:event_MenuAProveedoresActionPerformed

    private void MenuGCambioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGCambioUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuGCambioUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAAcercade;
    private javax.swing.JMenuItem MenuAInformeDeVentas;
    private javax.swing.JMenuItem MenuAPersonal;
    private javax.swing.JMenuItem MenuAProductos;
    private javax.swing.JMenuItem MenuAProveedores;
    private javax.swing.JMenuItem MenuAQuienesSomos;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenuItem MenuCCreditos;
    private javax.swing.JMenuItem MenuCRegistro;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenuItem MenuGCambioClave;
    private javax.swing.JMenuItem MenuGCambioUsuario;
    private javax.swing.JMenuItem MenuGSalir;
    private javax.swing.JMenuItem MenuGUsuarios;
    private javax.swing.JMenu MenuGestion;
    private javax.swing.JMenuItem MenuMDevoluciones;
    private javax.swing.JMenuItem MenuMPedidos;
    private javax.swing.JMenuItem MenuMTraslados;
    private javax.swing.JMenuItem MenuMVentas;
    private javax.swing.JMenu MenuMovimientos;
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
